// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use crate::ffi::*;
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -89801641;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__ffi__engine_is_running_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "engine_is_running",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_handle = <RustOpaqueMoi<VocomEngineHandle>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::ffi::engine_is_running(&api_handle))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__ffi__engine_poll_event_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "engine_poll_event",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_handle = <RustOpaqueMoi<VocomEngineHandle>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::ffi::engine_poll_event(&api_handle))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__ffi__engine_send_command_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "engine_send_command",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_handle = <RustOpaqueMoi<VocomEngineHandle>>::sse_decode(&mut deserializer);
            let api_cmd = <crate::engine_handle::EngineCommand>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::ffi::engine_send_command(&api_handle, api_cmd)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__ffi__engine_shutdown_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "engine_shutdown",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_handle = <RustOpaqueMoi<VocomEngineHandle>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::ffi::engine_shutdown(&api_handle)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__ffi__engine_start_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "engine_start",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_config_json = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::ffi::engine_start(api_config_json)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__ffi__viot_check_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "viot_check",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_transcript = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::ffi::viot_check(api_transcript))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__ffi__viot_execute_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "viot_execute",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_matched = <crate::ffi::FfiViotMatch>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::ffi::viot_execute(api_matched);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__ffi__viot_init_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "viot_init",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_esp_base_url = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::ffi::viot_init(api_esp_base_url))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: related_funcs

flutter_rust_bridge::frb_generated_moi_arc_impl_value!(VocomEngineHandle);

// Section: dart2rust

impl SseDecode for RustOpaqueMoi<VocomEngineHandle> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <usize>::sse_decode(deserializer);
        return decode_rust_opaque_moi(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for u128 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return inner.parse().unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::engine_handle::EngineCommand {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::engine_handle::EngineCommand::StartEngineNow;
            }
            1 => {
                let mut var_text = <String>::sse_decode(deserializer);
                return crate::engine_handle::EngineCommand::SubmitWakewordTranscript {
                    text: var_text,
                };
            }
            2 => {
                return crate::engine_handle::EngineCommand::GetTelemetry;
            }
            3 => {
                return crate::engine_handle::EngineCommand::PollTranscript;
            }
            4 => {
                return crate::engine_handle::EngineCommand::SpeakMockReply;
            }
            5 => {
                let mut var_text = <String>::sse_decode(deserializer);
                return crate::engine_handle::EngineCommand::SpeakText { text: var_text };
            }
            6 => {
                let mut var_halfDuplexMuteMic = <bool>::sse_decode(deserializer);
                return crate::engine_handle::EngineCommand::SetDuplexMode {
                    half_duplex_mute_mic: var_halfDuplexMuteMic,
                };
            }
            7 => {
                return crate::engine_handle::EngineCommand::GetDuplexMode;
            }
            8 => {
                return crate::engine_handle::EngineCommand::Shutdown;
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::ffi::FfiBargeInTelemetry {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_requested = <u64>::sse_decode(deserializer);
        let mut var_rejectedLowRms = <u64>::sse_decode(deserializer);
        let mut var_rejectedRenderRatio = <u64>::sse_decode(deserializer);
        let mut var_rejectedPersistence = <u64>::sse_decode(deserializer);
        let mut var_rejectedConfidence = <u64>::sse_decode(deserializer);
        let mut var_ducked = <u64>::sse_decode(deserializer);
        let mut var_stopped = <u64>::sse_decode(deserializer);
        let mut var_latencySamples = <usize>::sse_decode(deserializer);
        let mut var_latencyP50Ms = <Option<u64>>::sse_decode(deserializer);
        let mut var_latencyP95Ms = <Option<u64>>::sse_decode(deserializer);
        let mut var_rollingRequested = <u64>::sse_decode(deserializer);
        let mut var_rollingRejectedLowRms = <u64>::sse_decode(deserializer);
        let mut var_rollingRejectedRenderRatio = <u64>::sse_decode(deserializer);
        let mut var_rollingRejectedPersistence = <u64>::sse_decode(deserializer);
        let mut var_rollingRejectedConfidence = <u64>::sse_decode(deserializer);
        let mut var_rollingDucked = <u64>::sse_decode(deserializer);
        let mut var_rollingStopped = <u64>::sse_decode(deserializer);
        let mut var_rollingLatencySamples = <usize>::sse_decode(deserializer);
        let mut var_rollingLatencyP50Ms = <Option<u64>>::sse_decode(deserializer);
        let mut var_rollingLatencyP95Ms = <Option<u64>>::sse_decode(deserializer);
        let mut var_state = <String>::sse_decode(deserializer);
        let mut var_recentTransitions =
            <Vec<crate::ffi::FfiBargeInTransitionEntry>>::sse_decode(deserializer);
        return crate::ffi::FfiBargeInTelemetry {
            requested: var_requested,
            rejected_low_rms: var_rejectedLowRms,
            rejected_render_ratio: var_rejectedRenderRatio,
            rejected_persistence: var_rejectedPersistence,
            rejected_confidence: var_rejectedConfidence,
            ducked: var_ducked,
            stopped: var_stopped,
            latency_samples: var_latencySamples,
            latency_p50_ms: var_latencyP50Ms,
            latency_p95_ms: var_latencyP95Ms,
            rolling_requested: var_rollingRequested,
            rolling_rejected_low_rms: var_rollingRejectedLowRms,
            rolling_rejected_render_ratio: var_rollingRejectedRenderRatio,
            rolling_rejected_persistence: var_rollingRejectedPersistence,
            rolling_rejected_confidence: var_rollingRejectedConfidence,
            rolling_ducked: var_rollingDucked,
            rolling_stopped: var_rollingStopped,
            rolling_latency_samples: var_rollingLatencySamples,
            rolling_latency_p50_ms: var_rollingLatencyP50Ms,
            rolling_latency_p95_ms: var_rollingLatencyP95Ms,
            state: var_state,
            recent_transitions: var_recentTransitions,
        };
    }
}

impl SseDecode for crate::ffi::FfiBargeInTransitionEntry {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_atMs = <u64>::sse_decode(deserializer);
        let mut var_from = <String>::sse_decode(deserializer);
        let mut var_to = <String>::sse_decode(deserializer);
        let mut var_reason = <String>::sse_decode(deserializer);
        return crate::ffi::FfiBargeInTransitionEntry {
            at_ms: var_atMs,
            from: var_from,
            to: var_to,
            reason: var_reason,
        };
    }
}

impl SseDecode for crate::ffi::FfiEngineEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::ffi::FfiEngineEvent::BootStateChanged(var_field0);
            }
            1 => {
                let mut var_field0 =
                    <crate::realtime_pipeline::TranscriptEvent>::sse_decode(deserializer);
                return crate::ffi::FfiEngineEvent::TranscriptReady(var_field0);
            }
            2 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::ffi::FfiEngineEvent::BargeInTransition(var_field0);
            }
            3 => {
                let mut var_field0 = <crate::ffi::FfiBargeInTelemetry>::sse_decode(deserializer);
                return crate::ffi::FfiEngineEvent::TelemetrySnapshot(var_field0);
            }
            4 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::ffi::FfiEngineEvent::DuplexModeChanged(var_field0);
            }
            5 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::ffi::FfiEngineEvent::Error(var_field0);
            }
            6 => {
                return crate::ffi::FfiEngineEvent::Shutdown;
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::ffi::FfiViotMatch {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_label = <String>::sse_decode(deserializer);
        let mut var_endpoint = <String>::sse_decode(deserializer);
        let mut var_score = <f32>::sse_decode(deserializer);
        let mut var_matchedInput = <String>::sse_decode(deserializer);
        return crate::ffi::FfiViotMatch {
            label: var_label,
            endpoint: var_endpoint,
            score: var_score,
            matched_input: var_matchedInput,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<crate::ffi::FfiBargeInTransitionEntry> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::ffi::FfiBargeInTransitionEntry>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<crate::ffi::FfiEngineEvent> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::ffi::FfiEngineEvent>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::ffi::FfiViotMatch> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::ffi::FfiViotMatch>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::realtime_pipeline::TranscriptEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_text = <String>::sse_decode(deserializer);
        let mut var_sampleRate = <i32>::sse_decode(deserializer);
        let mut var_sampleCount = <usize>::sse_decode(deserializer);
        let mut var_decodeLatencyMs = <u128>::sse_decode(deserializer);
        return crate::realtime_pipeline::TranscriptEvent {
            text: var_text,
            sample_rate: var_sampleRate,
            sample_count: var_sampleCount,
            decode_latency_ms: var_decodeLatencyMs,
        };
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap() as _
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__ffi__engine_is_running_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__ffi__engine_poll_event_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__ffi__engine_send_command_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__ffi__engine_shutdown_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__ffi__engine_start_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__ffi__viot_check_impl(port, ptr, rust_vec_len, data_len),
        7 => wire__crate__ffi__viot_execute_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__ffi__viot_init_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::engine_handle::EngineCommand {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::engine_handle::EngineCommand::StartEngineNow => [0.into_dart()].into_dart(),
            crate::engine_handle::EngineCommand::SubmitWakewordTranscript { text } => {
                [1.into_dart(), text.into_into_dart().into_dart()].into_dart()
            }
            crate::engine_handle::EngineCommand::GetTelemetry => [2.into_dart()].into_dart(),
            crate::engine_handle::EngineCommand::PollTranscript => [3.into_dart()].into_dart(),
            crate::engine_handle::EngineCommand::SpeakMockReply => [4.into_dart()].into_dart(),
            crate::engine_handle::EngineCommand::SpeakText { text } => {
                [5.into_dart(), text.into_into_dart().into_dart()].into_dart()
            }
            crate::engine_handle::EngineCommand::SetDuplexMode {
                half_duplex_mute_mic,
            } => [
                6.into_dart(),
                half_duplex_mute_mic.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::engine_handle::EngineCommand::GetDuplexMode => [7.into_dart()].into_dart(),
            crate::engine_handle::EngineCommand::Shutdown => [8.into_dart()].into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::engine_handle::EngineCommand
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::engine_handle::EngineCommand>
    for crate::engine_handle::EngineCommand
{
    fn into_into_dart(self) -> crate::engine_handle::EngineCommand {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ffi::FfiBargeInTelemetry {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.requested.into_into_dart().into_dart(),
            self.rejected_low_rms.into_into_dart().into_dart(),
            self.rejected_render_ratio.into_into_dart().into_dart(),
            self.rejected_persistence.into_into_dart().into_dart(),
            self.rejected_confidence.into_into_dart().into_dart(),
            self.ducked.into_into_dart().into_dart(),
            self.stopped.into_into_dart().into_dart(),
            self.latency_samples.into_into_dart().into_dart(),
            self.latency_p50_ms.into_into_dart().into_dart(),
            self.latency_p95_ms.into_into_dart().into_dart(),
            self.rolling_requested.into_into_dart().into_dart(),
            self.rolling_rejected_low_rms.into_into_dart().into_dart(),
            self.rolling_rejected_render_ratio
                .into_into_dart()
                .into_dart(),
            self.rolling_rejected_persistence
                .into_into_dart()
                .into_dart(),
            self.rolling_rejected_confidence
                .into_into_dart()
                .into_dart(),
            self.rolling_ducked.into_into_dart().into_dart(),
            self.rolling_stopped.into_into_dart().into_dart(),
            self.rolling_latency_samples.into_into_dart().into_dart(),
            self.rolling_latency_p50_ms.into_into_dart().into_dart(),
            self.rolling_latency_p95_ms.into_into_dart().into_dart(),
            self.state.into_into_dart().into_dart(),
            self.recent_transitions.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::ffi::FfiBargeInTelemetry
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::ffi::FfiBargeInTelemetry>
    for crate::ffi::FfiBargeInTelemetry
{
    fn into_into_dart(self) -> crate::ffi::FfiBargeInTelemetry {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ffi::FfiBargeInTransitionEntry {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.at_ms.into_into_dart().into_dart(),
            self.from.into_into_dart().into_dart(),
            self.to.into_into_dart().into_dart(),
            self.reason.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::ffi::FfiBargeInTransitionEntry
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::ffi::FfiBargeInTransitionEntry>
    for crate::ffi::FfiBargeInTransitionEntry
{
    fn into_into_dart(self) -> crate::ffi::FfiBargeInTransitionEntry {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ffi::FfiEngineEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::ffi::FfiEngineEvent::BootStateChanged(field0) => {
                [0.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::ffi::FfiEngineEvent::TranscriptReady(field0) => {
                [1.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::ffi::FfiEngineEvent::BargeInTransition(field0) => {
                [2.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::ffi::FfiEngineEvent::TelemetrySnapshot(field0) => {
                [3.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::ffi::FfiEngineEvent::DuplexModeChanged(field0) => {
                [4.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::ffi::FfiEngineEvent::Error(field0) => {
                [5.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::ffi::FfiEngineEvent::Shutdown => [6.into_dart()].into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::ffi::FfiEngineEvent {}
impl flutter_rust_bridge::IntoIntoDart<crate::ffi::FfiEngineEvent> for crate::ffi::FfiEngineEvent {
    fn into_into_dart(self) -> crate::ffi::FfiEngineEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::ffi::FfiViotMatch {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.label.into_into_dart().into_dart(),
            self.endpoint.into_into_dart().into_dart(),
            self.score.into_into_dart().into_dart(),
            self.matched_input.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::ffi::FfiViotMatch {}
impl flutter_rust_bridge::IntoIntoDart<crate::ffi::FfiViotMatch> for crate::ffi::FfiViotMatch {
    fn into_into_dart(self) -> crate::ffi::FfiViotMatch {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::realtime_pipeline::TranscriptEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.text.into_into_dart().into_dart(),
            self.sample_rate.into_into_dart().into_dart(),
            self.sample_count.into_into_dart().into_dart(),
            self.decode_latency_ms.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::realtime_pipeline::TranscriptEvent
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::realtime_pipeline::TranscriptEvent>
    for crate::realtime_pipeline::TranscriptEvent
{
    fn into_into_dart(self) -> crate::realtime_pipeline::TranscriptEvent {
        self
    }
}

impl SseEncode for RustOpaqueMoi<VocomEngineHandle> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        let (ptr, size) = self.sse_encode_raw();
        <usize>::sse_encode(ptr, serializer);
        <i32>::sse_encode(size, serializer);
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for u128 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.to_string(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::engine_handle::EngineCommand {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::engine_handle::EngineCommand::StartEngineNow => {
                <i32>::sse_encode(0, serializer);
            }
            crate::engine_handle::EngineCommand::SubmitWakewordTranscript { text } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(text, serializer);
            }
            crate::engine_handle::EngineCommand::GetTelemetry => {
                <i32>::sse_encode(2, serializer);
            }
            crate::engine_handle::EngineCommand::PollTranscript => {
                <i32>::sse_encode(3, serializer);
            }
            crate::engine_handle::EngineCommand::SpeakMockReply => {
                <i32>::sse_encode(4, serializer);
            }
            crate::engine_handle::EngineCommand::SpeakText { text } => {
                <i32>::sse_encode(5, serializer);
                <String>::sse_encode(text, serializer);
            }
            crate::engine_handle::EngineCommand::SetDuplexMode {
                half_duplex_mute_mic,
            } => {
                <i32>::sse_encode(6, serializer);
                <bool>::sse_encode(half_duplex_mute_mic, serializer);
            }
            crate::engine_handle::EngineCommand::GetDuplexMode => {
                <i32>::sse_encode(7, serializer);
            }
            crate::engine_handle::EngineCommand::Shutdown => {
                <i32>::sse_encode(8, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::ffi::FfiBargeInTelemetry {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.requested, serializer);
        <u64>::sse_encode(self.rejected_low_rms, serializer);
        <u64>::sse_encode(self.rejected_render_ratio, serializer);
        <u64>::sse_encode(self.rejected_persistence, serializer);
        <u64>::sse_encode(self.rejected_confidence, serializer);
        <u64>::sse_encode(self.ducked, serializer);
        <u64>::sse_encode(self.stopped, serializer);
        <usize>::sse_encode(self.latency_samples, serializer);
        <Option<u64>>::sse_encode(self.latency_p50_ms, serializer);
        <Option<u64>>::sse_encode(self.latency_p95_ms, serializer);
        <u64>::sse_encode(self.rolling_requested, serializer);
        <u64>::sse_encode(self.rolling_rejected_low_rms, serializer);
        <u64>::sse_encode(self.rolling_rejected_render_ratio, serializer);
        <u64>::sse_encode(self.rolling_rejected_persistence, serializer);
        <u64>::sse_encode(self.rolling_rejected_confidence, serializer);
        <u64>::sse_encode(self.rolling_ducked, serializer);
        <u64>::sse_encode(self.rolling_stopped, serializer);
        <usize>::sse_encode(self.rolling_latency_samples, serializer);
        <Option<u64>>::sse_encode(self.rolling_latency_p50_ms, serializer);
        <Option<u64>>::sse_encode(self.rolling_latency_p95_ms, serializer);
        <String>::sse_encode(self.state, serializer);
        <Vec<crate::ffi::FfiBargeInTransitionEntry>>::sse_encode(
            self.recent_transitions,
            serializer,
        );
    }
}

impl SseEncode for crate::ffi::FfiBargeInTransitionEntry {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.at_ms, serializer);
        <String>::sse_encode(self.from, serializer);
        <String>::sse_encode(self.to, serializer);
        <String>::sse_encode(self.reason, serializer);
    }
}

impl SseEncode for crate::ffi::FfiEngineEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::ffi::FfiEngineEvent::BootStateChanged(field0) => {
                <i32>::sse_encode(0, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::ffi::FfiEngineEvent::TranscriptReady(field0) => {
                <i32>::sse_encode(1, serializer);
                <crate::realtime_pipeline::TranscriptEvent>::sse_encode(field0, serializer);
            }
            crate::ffi::FfiEngineEvent::BargeInTransition(field0) => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::ffi::FfiEngineEvent::TelemetrySnapshot(field0) => {
                <i32>::sse_encode(3, serializer);
                <crate::ffi::FfiBargeInTelemetry>::sse_encode(field0, serializer);
            }
            crate::ffi::FfiEngineEvent::DuplexModeChanged(field0) => {
                <i32>::sse_encode(4, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::ffi::FfiEngineEvent::Error(field0) => {
                <i32>::sse_encode(5, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::ffi::FfiEngineEvent::Shutdown => {
                <i32>::sse_encode(6, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::ffi::FfiViotMatch {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.label, serializer);
        <String>::sse_encode(self.endpoint, serializer);
        <f32>::sse_encode(self.score, serializer);
        <String>::sse_encode(self.matched_input, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<crate::ffi::FfiBargeInTransitionEntry> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::ffi::FfiBargeInTransitionEntry>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<crate::ffi::FfiEngineEvent> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::ffi::FfiEngineEvent>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::ffi::FfiViotMatch> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::ffi::FfiViotMatch>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::realtime_pipeline::TranscriptEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.text, serializer);
        <i32>::sse_encode(self.sample_rate, serializer);
        <usize>::sse_encode(self.sample_count, serializer);
        <u128>::sse_encode(self.decode_latency_ms, serializer);
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_u64::<NativeEndian>(self as _)
            .unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use crate::ffi::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_vocom_demo_rust_arc_increment_strong_count_RustOpaque_VocomEngineHandle(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<VocomEngineHandle>::increment_strong_count(ptr as _);
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_vocom_demo_rust_arc_decrement_strong_count_RustOpaque_VocomEngineHandle(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<VocomEngineHandle>::decrement_strong_count(ptr as _);
    }
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use crate::ffi::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();

    #[wasm_bindgen]
    pub fn rust_arc_increment_strong_count_RustOpaque_VocomEngineHandle(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<VocomEngineHandle>::increment_strong_count(ptr as _);
    }

    #[wasm_bindgen]
    pub fn rust_arc_decrement_strong_count_RustOpaque_VocomEngineHandle(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<VocomEngineHandle>::decrement_strong_count(ptr as _);
    }
}
#[cfg(target_family = "wasm")]
pub use web::*;
